### ISSUE TITLE
Inconsistent alarm variable type in alarm_control_panel entity

### ISSUE THREAD

**Issue by jshank** [BioSehnsucht/ha-elkm1#15]
ha-elkm1 version: 818b7f3
elkm1 library (gwww) 0.4.7
Home Assistant 0.74.0 (official docker container)

It seems that the alarm variable is typically a string array of values except when it's a string of `Entry Timer Running`

A few examples of state
```
Alarm=('No alarm active',)

Alarm=Entry Timer Running

Alarm=('Entrance delay active',)
```

**Comment by BioSehnsucht** [comment]
Interesting. Looks like the times it's an array are when I'm setting it using a helper function from @gwww 's library, the other time I'm setting it in my code.

**Comment by gwww** [comment]
I'm looking at the code right now. I think that the attributes are being pulled from the wrong place.

I have an update that I am about to push (later today) to the alarm_control_panel HA code. I've rewritten the async_update to massively simplify. Look for PR later today.

**Comment by gwww** [comment]
Part of the problem is the HA arm dialog. It is missing "arming" and "disarming" here:
https://github.com/home-assistant/home-assistant-polymer/blob/e048060c72a3e16e63e7f88ed5e40e9d96971686/src/dialogs/more-info/controls/more-info-alarm_control_panel.js#L137-L138

I will add this to the bug that @BioSehnsucht has already opened.

**Comment by jshank** [comment]
I wasn't sure why it was stored in an array, seems like it can't be in multiple states so a string makes more sense. But, my automations look at the first value of that array which broke for that specific condition. Looking forward to the big PR 😃

**Comment by gwww** [comment]
I don't think you should be using that info. According to one of the devs (@ballob) that info is "Extra stuff that is not standardized". I'm not exactly sure what he means by by (yet).

You can check out my convo with him at 5:18pm today on this Discord channel: https://discordapp.com/channels/330944238910963714/330990195199442944

Depending on what he comes back with I would be tempted to not populate that info. That would mean you need to look elsewhere to get the state.

The PR I've just pushed cleans up all the state code. However, in the UI, as @BioSehnsucht has mentioned and with an HA issue, the UI does not handle all the states. That means that there is a small hack (well commented) in the elk integration code.

All that said:
- I think that this issue should be closed
- Don't use the current attributes for automation
- The attributes as written should be cleaned up

I'm waiting for further instruction from the HA devs on the attributes next steps.

Here is the info from the devs:

balloob Today at 5:19 PM
Extra stuff that's not standardized
@gwww
gwww Today at 5:20 PM
Should I return empty? Is it used for debug only? Should automation rely on it?
OverloadUT Today at 5:27 PM
If you don't have any auxiliary information to report about the device that a user would reasonably expect to be able to access (to run automations on, etc) then yeah, just empty

**Comment by gwww** [comment]
How do you look at the attributes? I've cleaned them up but no idea how to see them or use them.

I think that having some attributes may be useful, as I understand what they are. Still learning though.

**Comment by jshank** [comment]
I usually examine them directly in Home Assistant in the States section. 

```
{
  "code_format": "[0-9]{4}([0-9]{2})?",
  "changed_by": null,
  "hidden": false,
  "Last Armed At": 0,
  "Last Disarmed At": 0,
  "Last User Number": null,
  "Last User At": 0,
  "Last User Name": null,
  "Last Keypad Number": null,
  "Last Keypad Name": null,
  "Readiness": "Ready to arm",
  "Arm Status": [
    "Disarmed"
  ],
  "Alarm": [
    "No alarm active"
  ],
  "friendly_name": "Home"
}
```

**Comment by gwww** [comment]
Thanks @jshank!! That helps.

I was cleaning up the attrs, while also fixing the bug. How do you feel about the following format for the attrs:

```
code_format: ^[0-9]{4}([0-9]{2})?$
changed_by: null
last_armed_at: 1533603859.574496
last_disarmed_at: 1533603859.593923
last_user_number: 1
last_user_at: 1533603838.924777
last_user_name: Glenn
last_keypad_number: 1
last_keypad_name: Lower Hall
arm_up_state: ready_to_arm
arm_status: disarmed
alarm: no_alarm_active
friendly_name: Main
```
I've renamed the attribute name to match closer to the names ElkM1 uses. The values are now all lower with underscores instead of blanks and the "alarm" works.

This follows the format of other devices, e.g.: sun.sun

**Comment by BioSehnsucht** [comment]
Ironically, I originally had lowercase and underscore names, then I prettified them so that they were more human readable, but it turns out that by default none of those will show up in HASS anyways. D'oh. I already annoyed people once by renaming them LOL. We'll get a few grumbles if we change them back... though it probably makes things better overall. I just wish there was a way to provide a "pretty" attribute name to the UI and also force it to appear at all in the first place, without adding a bunch of stuff to the HASS UI code.

Some of those attribute names are also on keypads, so if we're going to rename things again, we should do it everywhere. Due to the nature of how Elk works, some parts actually come from keypads and some from areas, and we have to make educated guesses (keypad change always goes first so if a keypad changed in the last second before the area state changed, then we can be reasonably sure that was the keypad that caused it).

The reason I put the state that is useful for automation in there is there's no where else to put it, from the point of view of the automation triggers. You've got state, and you've got attributes (aka device state attributes), and anything else would require making function calls from the script somehow into the HASS componenet/platform to query things, and there's not a pretty / convenient way of doing this as far as I know for an automation trigger or such.

There was discussion at one point in one of the HASS repos about trying to separate out attributes that should be recorded versus those that don't need to be (and only exist for informational purposes), to reduce the load on the history/database stuff. There was also a discussion about whether it made sense to record things that might be triggers, to correlate the trigger. But last I looked it didn't go anywhere. Currently everything is recorded... 

However, renaming things and so on should be a separate issue / etc from this...

**Comment by gwww** [comment]
Grumbling! Grumbling!! Yah, breaking changes are not nice. But I'd rather
we solidify the code while on alpha/beta than try and do the right thing
when it's in the HA platform.

I agree, we need to be consistent. I can create a PR for all of the the
device_state_attributes if we agree to the format.

Related, the time attrs don't seem to format right. Look at the times on
entity sun.sun I'll poke at that tomorrow.
______
Sent using an itsy bitsy keyboard. Expect typos and brevity.

**Comment by BioSehnsucht** [comment]
Lets continue the discussion in https://github.com/BioSehnsucht/ha-elkm1/issues/17
