### ISSUE TITLE
Omnistat2 Thermostat with Google Home Issue

### ISSUE THREAD

**Issue by regicsolutions** [BioSehnsucht/ha-elkm1#29]
I have two Omnistat2 Thermostat's connected to my elk m1 and they work perfect in the home assistant app but for some reason I'm unable to control them in the Google Home app. They just stay stuck on 32 degrees, when I try changing it, it resets it back to 32 degrees on the app but nothing ever happens on the thermostats. It does read the temp correctly but it's like it's in read-only mode...![image](https://user-images.githubusercontent.com/6157895/100185949-11f19200-2eb3-11eb-9fe2-d138893c9933.jpeg)

**Comment by BioSehnsucht** [comment]
I should have archived this repo previously, since the project has been merged into homeassistant itself long ago, and no further work is occurring here.

I suggest you repost this issue on the homeassistant repo, it will also get more eyes on the issue so more likely to be resolved sooner than later.
